name: API Call
'on':
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          PROJECT_PATH: app
          REQUIREMENT_PATH: /requirements.txt
      - name: Run a Python script
        run: python .github/workflows/api.py
